name: health-checkup-cicd
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Deploy to Vercel
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Apply Prisma Migrations
        run: pnpm prisma migrate deploy

      - name: Pull Vercel Project Configuration
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview for develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          vercel --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production for main)
        if: github.ref == 'refs/heads/main'
        run: |
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
